language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install flit future-fstrings
  - flit install
  - pip install hicpack
#virtualenv:
#  system_site_packages: true
script:
  - python hicpack/test.py