site_name: HiCPack Documentation
pages:
    - Home: index.md
    - Installation: installation.md
    - Examples: examples.md
    - Stages:
        - Alignment: alignment.md
        - Raw Contact Maps: raw_map.md
        - BackgroundModel: bg_model.md
#        - Visualization: visualization.md
        - TAD Calling: tad_calling.md
theme: readthedocs
repo_url: https://github.com/Naghipourfar/HiCPack
site_description: 'An Integrated package for Hi-C Data Analysis'