site_name: HiCPack Documentation
nav:
    - Home: index.md
    - Installation: installation.md
    - Tutorials: Tutorials.md
    - Stages:
        - Alignment: alignment.md
        - RawMappingMatrix: raw_map.md
        - BackgroundModel: bg_model.md
        - Visualization: visualization.md
        - TAD Calling: tad_calling.md
        - Statistics: stat.md
theme: readthedocs
repo_url: https://github.com/Naghipourfar/HiCPack
site_description: 'An Integrated package for Hi-C Data Analysis'