site_name: SeqLearner Documentation
nav:
    - Home: index.md
    - Installation: installation.md
theme: readthedocs
repo_url: http://github.com/EliHei/SeqLearn
site_description: 'An Integrated package for Hi-C Data Analysis'
'